# Data Inspection

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

## 1. Loading the Dataset

### Concept
Dataset loading is the process of importing data into Python for inspection and analysis.

Pandas provides the read_csv() function to load a CSV file into a DataFrame.

### Example
An organization may store customer details, transactions, sales, or machine learning training data in a CSV file.

### Importance
Loading the dataset is the first step in understanding its structure before performing Exploratory Data Analysis or building Machine Learning models.

In [6]:
df = pd.read_csv("ml_training_data.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset shape: (5, 3)

   Study_Hours  Attendance  Exam_Marks
0            2          60          50
1            3          65          55
2            4          75          65
3            5          85          75
4            6          95          90

## 2. Dataset Dimensions

### Concept
Dataset dimensions describe the size of a dataset.

- Rows represent records or observations.
- Columns represent variables or features.

The shape attribute returns the number of rows and columns.

### Example
A dataset with 1,000 rows and 8 columns contains 1,000 records and 8 variables.

### AI/ML Relevance
Dataset dimensions help us understand how much data is available for analysis and model development.

In [7]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Dataset dimensions:", df.shape)

Number of rows: 5
Number of columns: 3
Dataset dimensions: (5, 3)

## 3. Column Names

### Concept
Column names identify the variables present in a dataset.

### Example
Columns in a training dataset may represent age, salary, experience, department, or a target label.

### Importance
Inspecting column names helps us understand the available information and identify possible input features, target variables, and identifier columns.

In [8]:
print("Column names:")
print(df.columns.tolist())

print("\nTotal number of columns:", len(df.columns))

Column names:
['Study_Hours', 'Attendance', 'Exam_Marks']

Total number of columns: 3

## 4. Dataset Index

### Concept
The index identifies the rows in a Pandas DataFrame. By default, Pandas assigns integer labels starting from zero.

An index is different from an identifier column such as Customer_ID or Employee_ID.

### Importance
Understanding the index helps us avoid mistakenly treating row labels as meaningful predictive features.

In [9]:
print("Dataset index:")
print(df.index)

print("\nFirst five index values:")
print(df.index[:5])

Dataset index:
RangeIndex(start=0, stop=5, step=1)

First five index values:
RangeIndex(start=0, stop=5, step=1)

## 5. Using head()

### Concept
The head() method displays the first five rows by default.

### Importance
It helps us inspect column names, example values, data organization, and possible unusual entries.

In [10]:
df.head()

   Study_Hours  Attendance  Exam_Marks
0            2          60          50
1            3          65          55
2            4          75          65
3            5          85          75
4            6          95          90

## 6. Using tail()

### Concept
The tail() method displays the last five rows by default.

### Importance
It helps us inspect records at the end of the dataset and check for unusual or unexpected values.

In [11]:
df.tail()

   Study_Hours  Attendance  Exam_Marks
0            2          60          50
1            3          65          55
2            4          75          65
3            5          85          75
4            6          95          90

## 7. Using sample()

### Concept
The sample() method selects random rows from a DataFrame.

### Example
A company may inspect a small random sample of transactions rather than manually viewing every record.

### Importance
Random sampling helps us examine records from different parts of the dataset.

In [12]:
df.sample(n=min(5, len(df)), random_state=42)

   Study_Hours  Attendance  Exam_Marks
1            3          65          55
4            6          95          90
2            4          75          65
0            2          60          50
3            5          85          75

## 8. Using info()

### Concept
The info() method provides information about the DataFrame, including the number of entries, column names, non-null counts, data types, and memory usage.

### Importance
It helps identify columns that may contain missing values and data types that may need further investigation.

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Study_Hours  5 non-null      int64
 1   Attendance   5 non-null      int64
 2   Exam_Marks   5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

## 9. Using describe()

### Concept
The describe() method generates descriptive statistics for numerical columns by default.

It includes:
- Count
- Mean
- Standard deviation
- Minimum and maximum
- Quartiles

### Importance
These statistics help us understand the range, center, and spread of numerical variables.

In [14]:
df.describe()

       Study_Hours  Attendance  Exam_Marks
count     5.000000    5.000000    5.000000
mean      4.000000   76.000000   67.000000
std       1.581139   14.317821   16.046807
min       2.000000   60.000000   50.000000
25%       3.000000   65.000000   55.000000
50%       4.000000   75.000000   65.000000
75%       5.000000   85.000000   75.000000
max       6.000000   95.000000   90.000000

## 10. Using dtypes

### Concept
The dtypes attribute displays the data type of each column.

Common data types include:
- int64: integer values
- float64: decimal values
- object: often text or mixed values
- bool: Boolean values
- datetime64: date and time values

### AI/ML Relevance
Incorrect data types can cause problems during analysis and model preparation.

In [15]:
print(df.dtypes)

Study_Hours    int64
Attendance     int64
Exam_Marks     int64
dtype: object

## 11. Using nunique()

### Concept
The nunique() method counts the number of distinct values in each column. By default, missing values are excluded.

### Importance
It helps identify columns with few categories, columns with many distinct values, and possible identifier columns.

In [16]:
print("Unique values in each column:")
print(df.nunique())

Unique values in each column:
Study_Hours    5
Attendance     5
Exam_Marks     5
dtype: int64

## 12. Using value_counts()

### Concept
The value_counts() method counts how frequently each value occurs in a column.

### Example
A dataset may contain different departments, product categories, or customer groups.

### Importance
Frequency counts help identify common categories, rare categories, and possible class imbalance.

In [17]:
categorical_columns = df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

if categorical_columns:
    column = categorical_columns[0]

    print("Selected column:", column)
    print("\nValue counts:")
    print(df[column].value_counts(dropna=False))

    print("\nPercentage distribution:")
    print(
        (df[column].value_counts(normalize=True, dropna=False) * 100)
        .round(2)
    )
else:
    print("No text or categorical columns detected.")

No text or categorical columns detected.

## 13. Identifying Numerical Columns

### Concept
Numerical features represent quantities or measurable values.

Examples include age, salary, price, quantity, and sales.

Numerical features can be discrete, such as the number of products sold, or continuous, such as weight or height.

### Importance
Identifying numerical columns helps us decide which statistical calculations and visualizations to use.

In [18]:
numerical_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

print("Numerical columns:")
print(numerical_columns)

print("\nNumber of numerical columns:", len(numerical_columns))

Numerical columns:
['Study_Hours', 'Attendance', 'Exam_Marks']

Number of numerical columns: 3

## 14. Identifying Categorical Columns

### Concept
Categorical features represent labels or groups rather than measurable quantities.

Examples include department, city, product category, and payment method.

### Importance
Categorical columns can be examined using frequency tables and bar charts. Some categorical variables may be stored as numbers, so their meanings should also be checked.

In [19]:
categorical_columns = df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("Categorical or text columns:")
print(categorical_columns)

print("\nNumber of detected categorical columns:", len(categorical_columns))

Categorical or text columns:
[]

Number of detected categorical columns: 0

## 15. Identifying Date/Time Columns

### Concept
Date/time columns contain dates, times, or timestamps.

Examples include order date, joining date, and transaction timestamp.

### Importance
Date/time columns can help us identify trends, seasonal patterns, and changes over time.

In [20]:
datetime_columns = df.select_dtypes(
    include=["datetime", "datetimetz"]
).columns.tolist()

possible_date_columns = [
    col for col in df.columns
    if any(word in col.lower() for word in ["date", "time", "timestamp"])
]

print("Columns stored as datetime:")
print(datetime_columns)

print("\nColumns with possible date/time names:")
print(possible_date_columns)

Columns stored as datetime:
[]

Columns with possible date/time names:
[]

In [ ]:
## 16. Identifying Identifier Columns

### Concept
Identifier columns are used to distinguish records or entities.

Examples include Customer_ID, Employee_ID, Transaction_ID, and Order_ID.

### Importance
Identifiers may contain many unique values but may not provide useful predictive information. They should be evaluated before being used as Machine Learning features.